### ISSUE TITLE
Uservoice widget very annoying on iphone

### ISSUE THREAD

**Issue by artash** [freecar/freecar-web#44] opened 2013-07-25 16:29 UTC
Uservoice widget overlaps with the page content in iphone/safari. It also slows down the scrolling (widget rendering slow when you scroll). 

It's extremely useful on web, but maybe we shall turn it off for mobile clients.

**Comment by grigy** [comment] 2013-07-26 18:54
duplicate of #49

**Closed as completed by grigy** 2013-07-26 18:54 UTC
