### ISSUE TITLE
After login Gray layer is shown

### ISSUE THREAD

**Issue by Arshaku** [freecar/freecar-web#31] opened 2013-07-24 10:30 UTC
After login Gray layer is shown. It disappears when you mouse-click on it. 
![bug](https://f.cloud.github.com/assets/3396881/847900/021ee23c-f44c-11e2-8743-2d94d9ccc51b.png)

**Comment by grigy** [comment] 2013-07-25 11:56
should be fixed. please check and close

**Closed as completed** 2013-07-25 13:19 UTC
Labels: bug

**Comment by artash** [comment] 2013-07-25 16:16
this was a duplicate of #36
